version: 0.2

phases:
  install:
    commands:
      - echo "Installing npm dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React application..."
      - npm run build
  post_build:
    commands:
      - echo "Copying build artifacts to S3..."
      - aws s3 sync ./build s3://netflix-clone-bucket-007/ --delete # Replace with your S3 bucket name

artifacts:
  files:
    - '**/*'
  base-directory: build # This specifies where the built files are located for potential artifact storage

